#!/bin/bash

input=$1

if [[ $# -gt 1 ]]; then
  theme=$2
  if [[ $# -gt 2 ]]; then
    trans=$3
  else
    trans=slide
  fi
else
  theme=serif
  trans=cube
fi

jupyter nbconvert ${input}.ipynb \
   --to slides \
   --SlidesExporter.reveal_theme=${theme}  \
   --SlidesExporter.reveal_scroll=True \
   --SlidesExporter.reveal_transition=${trans} \
   --reveal-prefix reveal.js

# https://medium.com/learning-machine-learning/present-your-data-science-projects-with-jupyter-slides-75f20735eb0f

mv ${input}.slides.html ${input}.html

