#!/bin/bash

input=$1

if [[ $# -gt 1 ]]; then
  theme=$2
else
  theme=serif
fi

jupyter nbconvert ${input}.ipynb \
   --to slides \
   --SlidesExporter.reveal_theme=${theme}  \
   --SlidesExporter.reveal_scroll=True \
   --SlidesExporter.reveal_transition=cube \
   --reveal-prefix reveal.js

# https://medium.com/learning-machine-learning/present-your-data-science-projects-with-jupyter-slides-75f20735eb0f

mv ${input}.slides.html ${input}.html

